<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="restaurants.xsl" type="text/xsl"?>

<!DOCTYPE catalogue [
  <!NOTATION jpeg SYSTEM "image/jpeg">
  <!ENTITY restaurant1_image PUBLIC "restaurant1_image_identifier" "https://raw.githubusercontent.com/reo101/xml-project/master/images/restaurants/restaurant1.jpg" NDATA jpeg>
  <!ENTITY restaurant2_image PUBLIC "restaurant2_image_identifier" "https://raw.githubusercontent.com/reo101/xml-project/master/images/restaurants/restaurant2.jpg" NDATA jpeg>
  <!ENTITY restaurant3_image PUBLIC "restaurant3_image_identifier" "https://raw.githubusercontent.com/reo101/xml-project/master/images/restaurants/restaurant3.jpg" NDATA jpeg>
  <!ENTITY restaurant4_image PUBLIC "restaurant4_image_identifier" "https://raw.githubusercontent.com/reo101/xml-project/master/images/restaurants/restaurant4.jpg" NDATA jpeg>
  <!ENTITY restaurant5_image PUBLIC "restaurant5_image_identifier" "https://raw.githubusercontent.com/reo101/xml-project/master/images/restaurants/restaurant5.jpg" NDATA jpeg>
  <!ENTITY restaurant6_image PUBLIC "restaurant6_image_identifier" "https://raw.githubusercontent.com/reo101/xml-project/master/images/restaurants/restaurant6.jpg" NDATA jpeg>
  <!ENTITY restaurant7_image PUBLIC "restaurant7_image_identifier" "https://raw.githubusercontent.com/reo101/xml-project/master/images/restaurants/restaurant7.jpg" NDATA jpeg>
  <!ELEMENT catalogue (types,regions,restaurants)>
  <!ATTLIST catalogue 
    xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation CDATA #FIXED "restaurants.xsd">
  <!ELEMENT types (type+)>
  <!ELEMENT type (#PCDATA)>
  <!ATTLIST type id ID #IMPLIED>
  <!ATTLIST type idref IDREF #IMPLIED>
  <!ELEMENT regions (region+)>
  <!ELEMENT region (#PCDATA)>
  <!ATTLIST region id ID #IMPLIED>
  <!ATTLIST region idref IDREF #IMPLIED>
  <!ELEMENT restaurants (restaurant+)>
  <!ELEMENT restaurant (name,type,region,address,rating,image)>
  <!ATTLIST restaurant id ID #REQUIRED>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ELEMENT rating (#PCDATA)>
  <!ELEMENT image EMPTY>
  <!ATTLIST image source ENTITY #REQUIRED>
]>

<catalogue 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="restaurants.xsd">
  <types>
    <type id="sushi">Sushi</type>
    <type id="srabska">Srabska</type>
    <type id="morska">Morska</type>
    <type id="bulgarska">Bulgarska</type>
    <type id="pizza">Pizza</type>
  </types>
  <regions>
    <region id="sofia">Sofia</region>
    <region id="burgas">Burgas</region>
    <region id="stara_zagora">Stara Zagora</region>
    <region id="varna">Varna</region>
  </regions>
  <restaurants>
    <restaurant id="restaurant1">
      <name>SASA Fashion Food</name>
      <type idref="sushi"/>
      <region idref="sofia"/>
      <address>bul. Cherni vrah 100</address>
      <rating>4.0</rating>
      <image source="restaurant1_image"/>
    </restaurant>
    <restaurant id="restaurant2">
      <name>SUSHI EXPRESS</name>
      <type idref="sushi"/>
      <region idref="varna"/>
      <address>Centar, bul. Praga 20</address>
      <rating>4.9</rating>
      <image source="restaurant2_image"/>
    </restaurant>
    <restaurant id="restaurant3">
      <name>Srabski Restorant BEST</name>
      <type idref="srabska"/>
      <region idref="sofia"/>
      <address>bul. Nikolaj J. Vapcarov 1</address>
      <rating>4.4</rating>
      <image source="restaurant3_image"/>
    </restaurant>
    <restaurant id="restaurant4">
      <name>Franco Pica</name>
      <type idref="pizza"/>
      <region idref="burgas"/>
      <address>Ul. Han Asparuh 37</address>
      <rating>4.2</rating>
      <image source="restaurant4_image"/>
    </restaurant>
    <restaurant id="restaurant5">
      <name>Kapitan Kuk</name>
      <type idref="morska"/>
      <region idref="sofia"/>
      <address>pl. Narodno Sabranie 4</address>
      <rating>4.0</rating>
      <image source="restaurant5_image"/>
    </restaurant>
    <restaurant id="restaurant6">
      <name>Zlatna srabska skara</name>
      <type idref="srabska"/>
      <region idref="stara_zagora"/>
      <address>bul. Nikola Petkov 17</address>
      <rating>4.8</rating>
      <image source="restaurant6_image"/>
    </restaurant>
    <restaurant id="restaurant7">
      <name>Trite Shterki</name>
      <type idref="bulgarska"/>
      <region idref="varna"/>
      <address>bul. Dondukov 60A</address>
      <rating>3.9</rating>
      <image source="restaurant7_image"/>
    </restaurant>
  </restaurants>
</catalogue>
